### ISSUE TITLE
Bugs: hide-and-seek

### ISSUE THREAD

**Issue by rebaz36** [rebaz36/Portfolio#17]
# [Bugs: hide-and-seek](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/debugging/exercises/hide_and_seek.md)

**Comment by Apatakiti** [comment]
Hi Rebaz36, 👋🏻👋🏻
Good job so far!🔥🔥🔥💪🏻💪🏻

**Highlights**

-  No Linters error ✅✅
-  Clean code ✅✅
-  Great working on the Functionality ✅✅
-  Required Changes ♻️
-  Check the comments under the review.

- I found that the navigation menu in the mobile version still displays after clicking the internal links and I have tried my best to correct it but it's time-consuming.


**Optional suggestions**
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.
I found that the navigation menu in the mobile version still displays after clicking the internal links.
I have tried my best to correct it but it's time-consuming.


- I suggest you work on it to have better functionality.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
